name: Auto Responder

on: [pull_request, issues]

jobs:
  autoresponder:
    runs-on: ubuntu-latest
    steps:
    - with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your Message, Mantainers are on holiday'
        pr-message: 'Thank you for your PR, Mantainers are on holiday'

